### ISSUE TITLE
multiply defined symbols

### ISSUE THREAD

**Issue by JonasFocke01** [jannic/rp2040-flash#15]
Hello and sorry, that i had to came here to ask such things.

I tried to implement the flash reading/writing to save some configuration.  
I have poked around myself for a couple of days now to get this to work but it seems, that im unable to even get this library working correctly.  
I fully understand, that this is more like a work-in-progress thingy as one can read [here](https://github.com/rp-rs/rp-hal/issues/257), so close this issue if this project is not intended for users yet.  

I got writing/reading working one time, but it was very unreliable, so i updated some crates to fix that and now im stuck even getting things to compile/link. The compiler says `warning: Linking globals named '__subsf3': symbol multiply defined!` and `error: failed to load bitcode of module "rp2040_hal-cdae1f1f5b4a9470.rp2040_hal.6a3169b15416d485-cgu.03.rcgu.o":`. I suspect, that the error has something to do with my versions conflicting, but everything i try results in other errors that im unable to fix.  
This is my `Cargo.toml`:
```toml
[package]
name = "xxx"
version = "0.4.15"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt = "0.7.3"
panic-halt = "0.2.0"
rp-pico = "0.8.0"
cortex-m = "0.7.2"
rp2040-hal = { version = "0.9.1" }
fugit = "0.3.5"
usb-device= "0.2.9"
usbd-serial = "0.1.1"
embedded-hal = "0.2.5"
smart-leds = "0.3.0"
ws2812-pio = "0.7.0"
pio-proc = "0.2.0"
pio = "0.2.0"
rw_strip_macros = { path = "src/macros" }
format_no_std = "1.0.2"
rp2040-flash = "0.5.1"
defmt = "0.3.10"
# embedded-dma = "0.2.0"
# rp2040-flash = "0.4.0"

[[bin]]
name = "rw_strip"
test = false
bench = false

[profile.release]
opt-level = 3
lto = 'fat'

[profile.dev]
opt-level = 3
lto = 'fat'
```

Can you help me?
